# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://help.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/modget-core"
    schedule:
      interval: "daily"
  - package-ecosystem: "gradle"
    directory: "/modget-1.16"
    schedule:
      interval: "daily"
  - package-ecosystem: "gradle"
    directory: "/modget-1.16-compat"
    schedule:
      interval: "daily"
  - package-ecosystem: "gradle"
    directory: "/modget-1.17"
    schedule:
      interval: "daily"
  - package-ecosystem: "gradle"
    directory: "/modget-1.17-compat"
    schedule:
      interval: "daily"
  - package-ecosystem: "gradle"
    directory: "/modget-1.19"
    schedule:
      interval: "daily"
  - package-ecosystem: "gradle"
    directory: "/modget-1.19-compat"
    schedule:
      interval: "daily"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
